<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_TextBoxA</name>
   <tag></tag>
   <elementGuidId>f4f5bcc2-14d5-484c-a32a-f25f6cb36b45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[normalize-space()='A']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
