<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ClickMe_JavaScript</name>
   <tag></tag>
   <elementGuidId>02494da7-8f0b-40fd-9932-2f2d41ed7c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CLICK ME!!&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b9a43c6c-7acd-4083-b9c9-6f9489faa18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-lg dropdown-toggle</value>
      <webElementGuid>b6b45b18-9ae8-4f13-a7ad-683c9e25ad59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec1e9ec9-9ee2-4692-bc2b-7b536b36f289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button2</value>
      <webElementGuid>550ece73-cd1f-420c-bfd8-d11ec2f01682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>0be9f582-ea5c-4997-897f-4ffe3a1113ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#myModalJSClick</value>
      <webElementGuid>b116e066-244b-4416-8c7f-40b56582182a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLICK ME!!</value>
      <webElementGuid>912c70b5-4b5b-4352-b4c0-8d630faead76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button2&quot;)</value>
      <webElementGuid>12b5d182-8b35-4958-89ee-4ce1f24d829b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button2']</value>
      <webElementGuid>1db4f37a-aabc-4414-8974-0c36d0b9d047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript click.'])[1]/following::span[1]</value>
      <webElementGuid>90f5ca8a-49ce-43cb-8da1-e1d599ce562c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action Move &amp; Click'])[1]/preceding::span[1]</value>
      <webElementGuid>efabc094-3ec2-4edf-b42c-bcca1309140a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a WebElement based on the button below.'])[3]/preceding::span[1]</value>
      <webElementGuid>93f404f2-e8ff-466e-be22-e9ee22010f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLICK ME!!']/parent::*</value>
      <webElementGuid>d922f3ee-8a1e-4e28-83a0-143187a4023e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
      <webElementGuid>f82b876b-3a80-47a7-8a6e-55317da4b124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = 'button' and @id = 'button2' and (text() = 'CLICK ME!!' or . = 'CLICK ME!!')]</value>
      <webElementGuid>70ac8b26-e5af-45eb-9d27-91a38d482593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
