<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text</name>
   <tag></tag>
   <elementGuidId>9c5f5f3a-5122-471f-9f26-f6a40e2a0c2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uploaded-files' and (text() = '
    0d0ebedbc32e7fb8a32c22de71888e61.gif
  ' or . = '
    0d0ebedbc32e7fb8a32c22de71888e61.gif
  ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uploaded-files</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uploaded-files']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;0d0ebedbc32e7fb8a32c22de71888e61.gif&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff50abbd-39ea-43e3-a226-e4cc37f86da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploaded-files</value>
      <webElementGuid>8dc55559-d17d-49d0-9fa5-5281b5fcf152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel text-center</value>
      <webElementGuid>eda092e1-15dd-43cc-b2e7-012b5a78c083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    0d0ebedbc32e7fb8a32c22de71888e61.gif
  </value>
      <webElementGuid>bf6704be-9dee-470f-a275-a0bdbac2f5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploaded-files&quot;)</value>
      <webElementGuid>3f22bed7-5727-459d-ab32-3f9e3b5cf6d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uploaded-files']</value>
      <webElementGuid>70d8ecfd-3a91-463d-b0ba-bacc1502bfb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div</value>
      <webElementGuid>498ee6c9-06e9-438c-8c5a-cc038993bfab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Uploaded!'])[1]/following::div[1]</value>
      <webElementGuid>22569291-0047-494a-b2de-f3b33526353a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elemental Selenium'])[1]/preceding::div[1]</value>
      <webElementGuid>1a6b38bd-92b7-4d2a-80eb-639f96619322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0d0ebedbc32e7fb8a32c22de71888e61.gif']/parent::*</value>
      <webElementGuid>d2ddfae8-7701-4e92-bf2e-363342111eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>960d78b5-0fc7-4185-a815-d9a7ee885862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uploaded-files' and (text() = '
    0d0ebedbc32e7fb8a32c22de71888e61.gif
  ' or . = '
    0d0ebedbc32e7fb8a32c22de71888e61.gif
  ')]</value>
      <webElementGuid>eae31f50-5c43-488f-a75c-ecd1f75c3429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
