<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ExpandMenu</name>
   <tag></tag>
   <elementGuidId>0fa17740-5d24-44bc-b806-93c0b0ba89d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>btn_ExpandMenu</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
